version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    command: npm start
    volumes: 
      - logs:/usr/app/logs
      - ./src:/usr/app/src
    ports:
      - "${BACKEND_PORT}:${BACKEND_PORT}"
      - '9229:9229'
    env_file:
      - .env
    depends_on:
      - db
    restart: always
    networks:
      - my-net

  db: 
    image: postgres:13.1-alpine
    restart: always
    ports:
      - ${DB_PORT}:5432
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - database:/var/lib/postgres
    networks:
      - my-net
  
  pgadmin:
    image: dpage/pgadmin4:5.6
    restart: always
    logging:
      driver: none
    ports: 
      - ${PGADMIN_PORT}:80
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}
    networks:
      - my-net

volumes:
  logs: 
  database:

networks:
  my-net:
    driver: bridge